# Generated by Django 5.0.3 on 2024-03-29 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('names', models.CharField(max_length=80)),
                ('surnames', models.CharField(max_length=80)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('names', models.CharField(max_length=80)),
                ('surnames', models.CharField(max_length=80)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('fav_topics', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
