# Generated by Django 5.0.3 on 2024-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='dni',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
