# Generated by Django 5.0.3 on 2024-04-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('schedule', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pubYear', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('issbn', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('pubDate', models.DateField()),
                ('condition', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('reserved', models.BooleanField()),
                ('sold', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.store')),
            ],
        ),
    ]
