# Generated by Django 5.0.4 on 2024-04-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_store_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(limit_choices_to={'id__in': ()}, on_delete=django.db.models.deletion.CASCADE, to='books.store'),
        ),
    ]
