# Generated by Django 5.0.4 on 2024-05-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_condition_alter_book_image_and_more'),
        ('books', '0007_alter_book_store_sale_turned'),
    ]

    operations = [
    ]
