# Generated by Django 5.0.4 on 2024-05-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_merge_20240503_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='book',
        ),
        migrations.RemoveField(
            model_name='turned',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='turned',
            name='client',
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(limit_choices_to={'id__in': (1, 2, 3, 4, 5)}, on_delete=django.db.models.deletion.CASCADE, to='books.store'),
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Turned',
        ),
    ]
