# Generated by Django 5.0.4 on 2024-05-31 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cadDate',
        ),
        migrations.AddField(
            model_name='card',
            name='cadMonth',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='card',
            name='cadYear',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.PositiveBigIntegerField(default=12000),
        ),
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(limit_choices_to={'id__in': (1, 2, 3, 4, 5)}, on_delete=django.db.models.deletion.CASCADE, to='books.store'),
        ),
    ]
