# Generated by Django 5.0.4 on 2024-05-31 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_card_caddate_card_cadmonth_card_cadyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(limit_choices_to={'id__in': (1, 2, 3, 4, 5)}, on_delete=django.db.models.deletion.CASCADE, to='books.store'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cadMonth',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='cadYear',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='wallet',
            field=models.PositiveBigIntegerField(),
        ),
    ]
