# Generated by Django 5.0.4 on 2024-06-07 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_store'),
        ('users', '0004_remove_admin_usertype_remove_client_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(limit_choices_to={'id__in': (1, 2, 3, 4, 5)}, on_delete=django.db.models.deletion.CASCADE, to='books.store'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
    ]
